### ISSUE TITLE
如何选择加载第几个控制器？

### ISSUE THREAD

**Issue by 18863346399** [liunianhuaguoyanxi/ZWTopSelectVcView#4]
如何在视图顺序不变的情况下，加载第2个或者第3个控制器呢？

**Comment by liunianhuaguoyanxi** [comment]
你好！稍后我会添加这样的接口，感谢反馈！

**Comment by liunianhuaguoyanxi** [comment]
已更新，可以在代理方法中设置参数，如：
//（可选）显示第几个子控制器，默认为第一个
-(NSInteger)showChildViewVcIndexInZWTopSelectVcView:(ZWTopSelectVcView *)topSelectVcView
{
    return 2;
}

**Comment by 18863346399** [comment]
感谢！已下载




------------------ 原始邮件 ------------------
发件人: "liunianhuaguoyanxi";<notifications@github.com>;
发送时间: 2017年8月14日(星期一) 下午4:05
收件人: "liunianhuaguoyanxi/ZWTopSelectVcView"<ZWTopSelectVcView@noreply.github.com>; 
抄送: "张海波"<1075923855@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [liunianhuaguoyanxi/ZWTopSelectVcView] 如何选择加载第几个控制器？ (#4)




已更新，可以在代理方法中设置参数，如：
 //（可选）显示第几个子控制器，默认为第一个
 -(NSInteger)showChildViewVcIndexInZWTopSelectVcView:(ZWTopSelectVcView *)topSelectVcView
 {
 return 2;
 }
