### ISSUE TITLE
动态初始化子控制器

### ISSUE THREAD

**Issue by Fish1992** [liunianhuaguoyanxi/ZWTopSelectVcView#6]
如果初始化是两个子控制器，十分钟后变为三个子控制器，在当前页面不退出的情况下，能实现让代理方法重新走一遍吗？请教，谢谢~~

**Comment by liunianhuaguoyanxi** [comment]
您好，已经更新，新增方法：
-(void)reloadWithChildControllerMutableArr:(NSMutableArray *)arr;
详情在demo中.
感谢反馈！

**Comment by Fish1992** [comment]
谢谢您，正好需要。👍   iOS 11适配上好像是有一些问题，具体没有仔细看，好像是路径那块儿的配置

**Comment by Fish1992** [comment]
控制器之间只能点击切换，不能滑动切换吗？self.topSelectVcView.isCloseSwipeGesture = NO; 设置了这个属性也不能滑动

**Comment by liunianhuaguoyanxi** [comment]
dome里展示，默认就可以滑动切换的，你看看是不是在你的应用里有响应链问题或者手势冲突了，打断点调试下。

**Comment by Fish1992** [comment]
有一个侧滑返回，几个单击手势，一个很小的scrollView（不在子控制器上），再就是tableView了，可以提供一个思路吗？除了侧滑返回，其它几个理论上都不会冲突

**Comment by liunianhuaguoyanxi** [comment]
在这几个地方打断点调试，一步步追踪, 缕清思路是关键.

**Comment by Fish1992** [comment]
OK~~  谢谢~  主控制器跟子控制器之间数据能够实时互传吗？比如在主控制器有一个输入框，发消息然后子控制器监测到事件的触发并进行数据更新，像聊天列表消息实时更新那种

**Comment by liunianhuaguoyanxi** [comment]
这只是一个很便捷的UI框架，数据交互要看你了，传值有很多方式，NSNotification，delegate，block等主要看你怎么设计架构，好好研究吧

**Comment by Fish1992** [comment]
好的~ thankYou~~
